version: "1.7"
services:
  app:
    build: .
    container_name: ${CONTAINER_NAME}
    hostname: "pochbot"
    volumes:
      - .:/code
    env_file:
      - .env
    mem_limit: "1g"
    mem_reservation: "512m"
    restart: 'always'