services:
  app:
    build: .
    container_name: pochbot-server
    command: python3 bot.py
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      - discbot=${discbot}
      - dora_channel_id=${dora_channel_id}